# Generated by Django 5.0.2 on 2024-02-25 23:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('stock_ticker_code', models.CharField(max_length=7)),
                ('stock_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
